#ifndef OPMIRROR_AWINDIB_PROTOCOL_H
#define OPMIRROR_AWINDIB_PROTOCOL_H

#define AWINDIB_HEADER_SIZE 46
#define AWINDIB_TAIL_SIZE 42
#define AWINDIB_LENGTH_OFFSET 30

#endif //OPMIRROR_AWINDIB_PROTOCOL_H
